version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/docker-entrypoint.sh
    # Will setup everything
    environment:
        DJANGO_SUPERUSER_PASSWORD: password
        DJANGO_SUPERUSER_USERNAME: root
        DJANGO_SUPERUSER_EMAIL: root@test.com
        POSTGRES_DB: pg_db
        POSTGRES_USER: admin_db
        POSTGRES_PASSWORD: MyD@t@65
    ports:
      - 8000:8000
    # All files here are connected with the docker container.
    volumes:
      - .:/app
    # Ensures that the second container runs first
    depends_on:
      - db

  db:
    image: postgres
    # Ensure that if postgresql stops it will restart
    restart: always
    environment:
      POSTGRES_DB: pg_db
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: MyD@t@65
    volumes:
      - .dbdata:/var/lib/postgresql
    # Not mandatory but will allow us to have access to the data in the DB
    ports:
      - 10320:5432

